### ISSUE TITLE
Use Different JSONDecoders

### ISSUE THREAD

**Issue by Psylynce** [UpBra/Winkie#3]
A user of this framework would need to be able to pass in different decoders for different requests or APIs they are consuming. A default decoder can be provided for basic needs. 

Could provide a type that confirms to `TopLevelDecoder` so that users can write their own decoders and parse other things besides JSON. 

https://github.com/UpBra/Winkie/blob/e75feae2237c0be3760004dc4cc80b863da52ed6/Winkie/Source/NetworkRequest.swift#L34

**Comment by UpBra** [comment]
This is just a default implementation for <ResultTypeDecodable> - If you need a different JSONDecoder you can override this implementation
